spring:
  profiles:
    active: dev   # abhi dev profile active rakhenge, dev matlab default dev config chalega, baad me production me sirf profile change karna hota hai
  application:
    name: enterpriseflow

server:
  port: 8080
